let money = 250000;
let income = 'Дополнительный доход: 80000';
let addExpenses = '500, 2500, 6300';
let deposit = true;
let mission = 2000000;
let period = 8;
console.log(typeof money);
console.log(typeof income);
console.log(typeof addExpenses);
console.log(income.length);
console.log('Период ' + period + ' месяцев. ' + 'Цель заработать ' + mission + ' рублей');
console.log(addExpenses.toLowerCase().split(' '));
let budgetDay = money / 30;
console.log(budgetDay);
let restBudgetDay = money % 30;
console.log(restBudgetDay);